version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - my-network
    volumes:
      - ./myvolume:/var/lib/mysql

  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./website1/www:/var/www/www.website1.local
    networks:
      - my-network
    environment:
      WORDPRESS_DB_PREFIX: wp1_
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - '81:80'
    volumes:
      - ./website2/www:/var/www/www.website2.local
    networks:
      - my-network
    environment:
      WORDPRESS_DB_PREFIX: wp2_
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
networks:
  my-network: